/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DecoratorTest {
    @Test
    void testDecorator() {
        Schtroumpf coquet = new SchtroumpfCoquet();
        Schtroumpf grognon = new SchtroumpfGrognon();
        assertEquals("quelle beau chapeau", coquet.discuter());
        assertEquals("Groumpf#&", grognon.discuter());
    }
}
