/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DecoratorTest {
    @Test
    void testDecorator() {
        assertEquals("quelle beau chapeau", new SchtroumpfCoquet().discuter());
        assertEquals("Groumpf#&", new SchtroumpfGrognon().discuter());
    }
}
