/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MagasinTest {
    @Test
    void testMagasinSingleton() {

        Magasin monMagasin1 = Magasin.getInstance();
        Magasin monMagasin2 = Magasin.getInstance();
        assertEquals(monMagasin1, monMagasin2);
    }
}
