/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class SupermanTest {

    @Test
    void testSingleton() throws InterruptedException {
        Superman superman1 = Superman.getInstance();
        Superman superman2 = Superman.getInstance();
        assertEquals(superman1, superman2);
    }

}
