@startuml ChainOfResponsability

interface Personnage {
    + recupererPierreInfinite(Temple): PierreInfinite
    + compterPierreGant(): int
}

class Thanos {
    - gant: List<PierreInfinite>
    + recupererPierreInfinite(Temple): PierreInfinite
    + compterPierreGant(): int
}

class BlackDwarf {
}

BlackDwarf .up.|> Personnage
Thanos .up.|> Personnage

class Temple {
    - protecteurs: List<Avengers>
    + ajouterProtecteur(Avengers)
    + recupererPierreInfinite(DemandeRecuperationPierreInfinite) : PierreInfinite
}

class DemandeRecuperationPierreInfinite {
    - demandeur: Personnage
}

class PierreInfinite

interface Avengers {
    + boolean gagneCombatContre(Personnage)
}

Ironman .up.|> Avenger
Spiderman .up.|> Avenger
Thor .up.|> Avenger

@enduml