@startuml ChainOfResponsability

class Thanos {
    - List<PierreInfinite> gant
    + recupererPierreInfinite(Temple): PierreInfinite
    + compterPierreGant(): int
}

class Temple {
    + recupererPierreInfinite() : PierreInfinite
}

class PierreInfinite

@enduml