@startuml ChainOfResponsability

Personnage -> DemandeRecuperationPierreInfinite : new
Personnage <-- DemandeRecuperationPierreInfinite
Personnage -> Temple : recupererPierreInfinite(DemandeRecuperationPierreInfinite)
Temple -> Avengers : gagneCombatContre(Personnage)
Temple <-- Avengers : false / true
Personnage <-- Temple : PierreInfinite / null

@enduml