@startuml ChainOfResponsability

BadGuy -> DemandeRecuperationPierreInfinite : new
BadGuy <-- DemandeRecuperationPierreInfinite
BadGuy -> Temple : recupererPierreInfinite(DemandeRecuperationPierreInfinite)
Temple -> Avengers : gagneCombatContre(BadGuy)
Temple <-- Avengers : false / true
BadGuy <-- Temple : PierreInfinite / null

@enduml