@startuml Command

class Maman {
    appelerATable(personne: Personne)
}

class Enfant {
    venirATableAQuatrePatte()
}

class Ado {
    venirATableEnRalant()
}


class ATableCommande {
    execute(personne: Personne)
}

Maman --> ATableCommande : utilise
ATableCommande --> Ado : utilise
ATableCommande --> Enfant : utilise

@enduml