@startuml Command

class Maman {
    appelerATable(personne: Personne)
}

class Enfant {
    venirATableAQuatrePatte()
}

class Ado {
    venirATableEnRalant()
}

interface Personne

class ATableCommande {
    execute(personne: Personne)
}

Enfant..|>Personne
Ado..|>Personne
@enduml