@startuml Composite
class Client {
}
interface Component {
     + execute(): String
}
class Composite {
     + addChild(child: Component): void
     + removeChildAt(index: int): void
     + getremoveChild(index: int): Component     
}
class Leaf

Client ..> Component : uses

Composite "1" *-- "many" Component : contains

Component <|-- Leaf
Component <|-- Composite
@enduml