@startuml interfaceAlias -- componentAlias : label <<stereotype>>
interface Forme {
     + dessiner() :void   
}
class Carre
class Dessin {
    + ajouter(Forme forme): Forme
}
class Rond

Dessin "1" *-- "many" Forme : contains

Forme <|-- Carre
Forme <|-- Dessin
Forme <|-- Rond
@enduml