@startuml Composite
interface Forme {
     + dessiner() :void   
}
class Carre
class Rond
class Dessin {
    - formes : List<Forme>
    + ajouter(Forme): void
}

Dessin "1" *-- "many" Forme : contains

Forme <|-- Carre
Forme <|-- Dessin
Forme <|-- Rond
@enduml