@startuml Decorator

interface Schtroumpf {
    + discuter()
}

class SchtroumpfGrognon {
}

class SchtroumpfCoquet {
}

class SchtroumpfDecorator {
    - schtroumpf: Schtroumpf
    + SchtroumpfDecorator(Schtroumpf)
    + saluer()
    + direAuRevoir()
}

SchtroumpfGrognon .up.|> Schtroumpf
SchtroumpfCoquet .up.|> Schtroumpf
SchtroumpfDecorator .up.|> Schtroumpf

@enduml{}