@startuml Decorator

interface Schtroumpf {
    + discuter()
}

class SchtroumpfGrognon {
}

class SchtroumpfCoquet {
}

class SchtroumpfDecorator {
    - schtroumpf: Schtroumpf
    + saluer()
    + direAuRevoir()
}

SchtroumpfGrognon-|>Schtroumpf
SchtroumpfCoquet-|>Schtroumpf
SchtroumpfDecorator-|>Schtroumpf

@enduml{}