@startuml Facade

package com.tetras.ingredient #DDDDDD {
    interface Ingredient

    class DoseUrineMusaraigne {
        {static} + prendre() : DoseUrineMusaraigne
    }

    class FeuilleSecheTout {
        {static} + prendre() : FeuilleSecheTout
    }
}

package com.tetras.materiel #AAAAAA {
    class Recipient {
        {static} + prendre() : Recipient
        + ajouter(Ingredient)
    }

    class PieceMolduArgent {
        {static} +  prendre() : PieceMolduArgent
        + couvrir(DoseUrineMusaraigne)
        + essuyer(FeuilleSecheTout)
        + transformer(): PieceOr
    }

    class PieceOr
}

package com.tetras.potion #FFFFFF {
    class PotionBrilleToutFacade {
        {static} - attendre(int)
        {static} + transformer(PieceMolduArgent, Recipient, DoseUrineMusaraigne, DoseUrineMusaraigne, FeuilleSecheTout) : PieceOr
    }
}
DoseUrineMusaraigne ..|> Ingredient
FeuilleSecheTout ..|> Ingredient
PieceMolduArgent .u.|> Ingredient

@enduml