@startuml FacadeSequence
actor PotionTest

PotionTest -> PieceMolduArgent : prendre
activate PieceMolduArgent
PotionTest <-- PieceMolduArgent: PieceMolduArgent
deactivate PieceMolduArgent
PotionTest -> Recipient : prendre
activate Recipient
PotionTest <-- Recipient : Recipient
deactivate Recipient
PotionTest -> DoseUrineMusaraigne: prendre
activate DoseUrineMusaraigne
PotionTest <-- DoseUrineMusaraigne: DoseUrineMusaraigne
deactivate DoseUrineMusaraigne
PotionTest -> DoseUrineMusaraigne: prendre
activate DoseUrineMusaraigne
PotionTest <-- DoseUrineMusaraigne: DoseUrineMusaraigne
deactivate DoseUrineMusaraigne
PotionTest -> FeuilleSecheTout: prendre
activate FeuilleSecheTout
PotionTest <-- FeuilleSecheTout: FeuilleSecheTout
deactivate FeuilleSecheTout

PotionTest -> PotionBrilleToutFacade: transformer(PieceMolduArgent, Recipient, DoseUrineMusaraigne, DoseUrineMusaraigne, FeuilleSecheTout)
activate PotionBrilleToutFacade
PotionBrilleToutFacade -> Recipient: ajouter(PieceMolduArgent)
PotionBrilleToutFacade -> PieceMolduArgent: couvrir(DoseUrineMusaraigne)
PotionBrilleToutFacade -> PieceMolduArgent: couvrir(DoseUrineMusaraigne)
PotionBrilleToutFacade -> PotionBrilleToutFacade: attendre(5mn)
PotionBrilleToutFacade -> PieceMolduArgent: essuyer(FeuilleSecheTout)
PotionBrilleToutFacade -> PieceMolduArgent: transfomer
activate PieceMolduArgent
PotionBrilleToutFacade <--> PieceMolduArgent: PieceOr
deactivate PieceMolduArgent
PotionBrilleToutFacade --> PotionTest: PieceOr
@enduml
