@startuml Factory
class Client
interface CommandExecutorFactory {
     + connect(host, port,user,password):void  
     + execute(query): Result  
     + close(): void
}
class MariaDbCommandExecutor
class OracleCommandExecutor
class Factory {
     # getCommandExecutor(TypeDb type): CommandExecutor
}
enum TypeDb

CommandExecutor <|.. MariaDbCommandExecutor
CommandExecutor <|..OracleCommandExecutor

Client ..> Factory : uses

@enduml