@startuml Iterator

class Serie {
    - nom: String
    - listeEpisode: List<Episode>
    + ajouter(episode: Episode)
    + getNom(): String
    + toString(): String
}

class Episode {
    + lire()
    + getNom(): String
    + toString(): String
}

class Iterator<Episode> {
    + next(): Episode
    + hasNext(): boolean
}

Serie..|>Iterator

@enduml