@startuml LazyInitialization

package com.tetras.librairie {
  class ServiceInfoEleve { 
      + getInformationEleve(int) : Eleve
  }
  note bottom of ServiceInfoEleve : getInformationEleve dure 900ms.
  class Eleve
}

package com.tetras.application #DDDDDD {
  class Application { 
      + start()
  }
  class ServiceInfoEleveCache { 
    - cache : Map<int,Eleve>  
    + getInformationEleve(int) : Eleve
  }
}

Application .. ServiceInfoEleveCache : utilise
ServiceInfoEleveCache .. ServiceInfoEleve : utilise


@enduml