@startuml
Application -> ServiceInfoEleveCache: récupère élève
ServiceInfoEleveCache -> ServiceInfoEleveCache: test presence élève dans le cache
ServiceInfoEleveCache -> ServiceInfoEleve: si élève non présent récupère met en cache
ServiceInfoEleveCache -> Application: retourne élève

@enduml