@startuml Listener

class Match {
    - support: PropertyChangeSupport
    - faitJeu: FaitJeu
    + genererFait(): FaitJeu
    + addPropertyChangeListener(PropertyChangeListener)
    + removePropertyChangeListener(PropertyChangeListener)
}

class FaitJeu

class Arbitre {
    + analyser(FaitJeu)
    + propertyChange(PropertyChangeEvent)
}

Arbitre .up.|> PropertyChangeListener
FaitJeu -left-o Match

@enduml