@startuml Memento

class Morceau {
    - nom
    + creerMemento(): MementoMorceau
    + restaurer(MementoMorceau)
}

class MementoMorceau {
    - nom
}

class LecteurMusique {
    - historiqueMorceau: List<MementoMorceau>
    + lire(Morceau)
    + lireMorceauPrecedent()
}

@enduml