@startuml Memento

class Morceau {
    - nom: String
    + creerMemento(): MementoMorceau
    + restaurer(MementoMorceau)
}

class MementoMorceau {
    - nom: String
}

class LecteurMusique {
    - stack: Stack<MementoMorceau>
    + lire(Morceau): String
    + lireMorceauPrecedent(): String
}

@enduml