@startuml Memento

== Save state ==
Client -> Originator : creerMemento
Originator -> Memento : new
Originator -> Memento : setState
Client <-- Originator : return memento

== Restore state ==
Client -> Originator : restaurerMemento(memento)
Originator -> Memento : getState

@enduml[]