@startuml Observer

class Observer<E> {
    + notify(element: E)
}

class Match {
    - listeObserver: List<Observer<FaitJeu>>
    + genererFait(): FaitJeu
    + register(observer: Observer<FaitJeu>)
}

class FaitJeu

class Arbitre {
    + analyser(fait: FaitJeu)
}

Arbitre..|>Observer

@enduml