@startuml Observer

class Observer<E> {
    + notify(E)
}

class Match {
    - listeFaitJeu: List<FaitJeu>
    + genererFait(): FaitJeu
    + register(Observer<FaitJeu>)
}

class FaitJeu

class Arbitre {
    + analyser(FaitJeu)
}

Arbitre .up.|> Observer

@enduml