@startuml Observer

interface Observer {
    + update(observable: Observable, fait: Object)
}

class Observable {
    + addObserver(observer: Observer)
    + setChanged()
    + notifyObservers()
}

class Match {
    + genererFait(): FaitJeu
}

class FaitJeu

class Arbitre {
    + analyser(fait: FaitJeu)
}

Arbitre .up.|> Observer
Match -up-|> Observable

@enduml