@startuml Prototype

class Prototype {
    + clone() : Prototype
}

class Client {
    + operation()
}


Client .r.> Prototype : prototype
Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2

@enduml