@startuml Todo

class Clone {
    - nom : String
    + Clone()
    + equals(Object) : boolean
    + clone() : Clone
}

class TransportDeTroupes {
    + sortirClone() : Clone
}

interface Cloneable

Clone ..|> Cloneable

@enduml