@startuml Proxy

class Schtroumpf {
    + saluer(Animal): String
}

class SchtroumpfDouanier

Schtroumpf<|--SchtroumpfDouanier

class Animal {
    - nom: String
}

class AnimalDangereux

Animal<|--AnimalDangereux

@enduml