@startuml State

class TonyStark {
    - state: State
    + changeState(state: State)
}

interface State  {
    + courir(): String
    + sauter(): String
}

class NormalState
class IronmanState

NormalState .up.|> State
IronmanState .up.|> State
TonyStark .up.|> State
TonyStark o-- State

@enduml