@startuml Strategy

class Frank {
    activerTourDeForce()
    activerEponge()
}

interface Brawler

interface StarPower

Frank .up.|> Brawler

TourDeForce .up.|> StarPower
Eponge .up.|> StarPower

@enduml