@startuml Strategy

class Frank {
}

interface Brawler {
    + activerStarPower(StarPowerStrategy): String
}

interface StarPowerStrategy {
    + activer(): String
}

Frank .up.|> Brawler

TourDeForce .up.|> StarPowerStrategy
Eponge .up.|> StarPowerStrategy

@enduml