@startuml Strategy

class Frank {
}

interface Brawler {
    + activerStarPower(StarPowerStrategy)
}

interface StarPowerStrategy {
    + activer()
}

Frank .up.|> Brawler

TourDeForce .up.|> StarPowerStrategy
Eponge .up.|> StarPowerStrategy

@enduml