@startuml Visitor

class Titre
class Gras
class Liste

abstract ElementTexte {
    - texte : String
    + getTexte(): String
    + {abstract} getHtml(): String
}

Liste -up-|> ElementTexte
Titre -up-|> ElementTexte
Gras -up-|> ElementTexte

@enduml