@startuml Visitor

class Titre
class Gras
class Liste

abstract ElementTexte {
    - texte : String
    + getTexte(): String
    + {abstract} getHtml(): String
}

ElementTexte <|-- Liste
ElementTexte <|-- Titre
ElementTexte <|-- Gras


@enduml