@startuml Visitor

interface Visitor {
    + void visit(Visitable)
    + void visit(Gras)
    + void visit(Liste)
    + void visit(Titre)
}

class HtmlVisitor

Visitor <|.. HtmlVisitor

interface Visitable {
    + void accept(Visitor)
}

class Titre {
    + void accept(Visitor)

}
class Gras {
    + void accept(Visitor)
}

class Liste {
    + void accept(Visitor)
}

abstract ElementTexte {
    - texte : String
    + getTexte(): String
}

Visitable <|.. ElementTexte

ElementTexte <|-- Liste
ElementTexte <|-- Titre
ElementTexte <|-- Gras


@enduml